CREATE SCHEMA USERSDB;

CREATE TABLE USERSDB.USERS
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(64) NOT NULL,
	USERNAME VARCHAR(64) NOT NULL,
	PASSWORD VARCHAR(128) NOT NULL,
	DELETED boolean default FALSE,
	ROLE VARCHAR(64),
	CONSTRAINT USERS_USERNAME_UINDEX UNIQUE (USERNAME)
);

CREATE TABLE USERSDB.GROUPS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME varchar(64) NOT NULL,
  DESCRIPTION varchar(300)
);
INSERT INTO USERSDB.USERS (ID, NAME, USERNAME, PASSWORD, ROLE) VALUES (1, 'Administrator', 'admin', 'admin', 'admin');
INSERT INTO USERSDB.GROUPS (ID, NAME, DESCRIPTION) VALUES (1, 'Group', 'The Default Group');
